import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactQueryProvider } from "./providers";
import "../styles/globals.css";

const vazirmatn = localFont({
  src: "../../public/fonts/vazirmatn-variable-font-wght.ttf",
  variable: "--font-vazirmatn",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatn.className} antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
